spring.application.name=FarmVerseApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/Farmverse
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# ==========================
# Hugging FaceAI
# ==========================
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=gsk_****************************************


groq.model.id=openai/gpt-oss-120b